/**
 * productCatalogMock — Phase 1 in-memory product catalog.
 *
 * This file is the only place that should be edited when adding, removing,
 * or updating products during Phase 1 development.
 *
 * Phase 2: this file is replaced by Firestore queries in
 * productCatalogService.ts. Delete it once the Firestore catalog is live.
 *
 * Products reflect typical Chilean supermarket items and serve as realistic
 * test data while the real catalog is being built.
 */
import type { ProductCatalog } from '@/domain'

export const mockProducts: ProductCatalog[] = [
  {
    id: 'prod-001',
    name: 'Azúcar',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 1,
    unit: 'kg',
    volumeTolerancePct: 10,
    category: 'despensa',
    searchKeywords: ['azucar', 'azucar blanca', 'azucar 1kg', 'iansa'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-002',
    name: 'Arroz',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 1,
    unit: 'kg',
    volumeTolerancePct: 10,
    category: 'despensa',
    searchKeywords: ['arroz', 'arroz 1kg', 'arroz grado 1'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-003',
    name: 'Leche Colun Semidescremada',
    type: 'specific',
    preferredBrand: 'Colun',
    strictBrand: true,
    targetQuantity: 1,
    unit: 'lt',
    volumeTolerancePct: 0,
    category: 'lacteos',
    searchKeywords: ['leche colun', 'colun semidescremada', 'leche semidescremada 1l'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-004',
    name: 'Leche Colun Semidescremada 200ml',
    type: 'specific',
    preferredBrand: 'Colun',
    strictBrand: true,
    targetQuantity: 200,
    unit: 'ml',
    volumeTolerancePct: 0,
    category: 'lacteos',
    searchKeywords: ['leche colun 200', 'colun 200ml', 'leche 200ml'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-005',
    name: 'Aceite Vegetal',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 1,
    unit: 'lt',
    volumeTolerancePct: 10,
    category: 'despensa',
    searchKeywords: ['aceite', 'aceite vegetal', 'aceite 1 litro'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-006',
    name: 'Harina',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 1,
    unit: 'kg',
    volumeTolerancePct: 10,
    category: 'despensa',
    searchKeywords: ['harina', 'harina 1kg', 'harina blanca'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-007',
    name: 'Fideos Lucchetti Spaghetti 5',
    type: 'specific',
    preferredBrand: 'Lucchetti',
    strictBrand: true,
    targetQuantity: 400,
    unit: 'gr',
    volumeTolerancePct: 0,
    category: 'despensa',
    searchKeywords: ['fideos', 'spaghetti', 'lucchetti', 'pastas lucchetti'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-008',
    name: 'Pan de Molde',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 1,
    unit: 'unit',
    volumeTolerancePct: 0,
    category: 'panaderia',
    searchKeywords: ['pan de molde', 'pan molde', 'pan lactal'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-009',
    name: 'Mantequilla',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 250,
    unit: 'gr',
    volumeTolerancePct: 10,
    category: 'lacteos',
    searchKeywords: ['mantequilla', 'mantequilla 250g', 'mantequilla sin sal'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-010',
    name: 'Coca-Cola Original 1.5L',
    type: 'specific',
    preferredBrand: 'Coca-Cola',
    strictBrand: true,
    targetQuantity: 1.5,
    unit: 'lt',
    volumeTolerancePct: 0,
    category: 'bebidas',
    searchKeywords: ['coca cola', 'coca-cola', 'coca cola 1.5', 'bebida cola'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-011',
    name: 'Huevos',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 12,
    unit: 'unit',
    volumeTolerancePct: 0,
    category: 'refrigerados',
    searchKeywords: ['huevos', 'huevo', 'docena huevos', 'huevos 12'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-012',
    name: 'Café Nescafé Tradición',
    type: 'specific',
    preferredBrand: 'Nescafé',
    strictBrand: true,
    targetQuantity: 170,
    unit: 'gr',
    volumeTolerancePct: 0,
    category: 'despensa',
    searchKeywords: ['nescafe', 'cafe nescafe', 'nescafe tradicion', 'cafe soluble'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-013',
    name: 'Sal',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 1,
    unit: 'kg',
    volumeTolerancePct: 10,
    category: 'despensa',
    searchKeywords: ['sal', 'sal fina', 'sal 1kg', 'sal de mesa'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-014',
    name: 'Detergente Omo Matic',
    type: 'specific',
    preferredBrand: 'Omo',
    strictBrand: true,
    targetQuantity: 3,
    unit: 'kg',
    volumeTolerancePct: 0,
    category: 'limpieza',
    searchKeywords: ['omo', 'detergente omo', 'omo matic', 'detergente ropa'],
    createdAt: new Date('2026-01-01'),
  },
  {
    id: 'prod-015',
    name: 'Papel Higiénico',
    type: 'generic',
    strictBrand: false,
    targetQuantity: 4,
    unit: 'unit',
    volumeTolerancePct: 0,
    category: 'limpieza',
    searchKeywords: ['papel higienico', 'papel toilet', 'papel 4 rollos'],
    createdAt: new Date('2026-01-01'),
  },
]
